spring:
  profiles:
    active: local # 기본 환경 선택
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB53Dialect

# local 환경
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    data: classpath:data-h2.sql # 시작할때 실행시킬 script
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none


#운영 환경
---
spring:
  config:
    activate:
      on-profile: set1
  profiles:
    include: read-db

server:
  port: 8081

---
spring:
  config:
    activate:
      on-profile: set2
  profiles:
    include: read-db

server:
  port: 8082