spring:
  profiles:
    active: local # 기본 환경 선택
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB53Dialect
# local 환경
---
spring:
  profiles: local
  datasource:
    data: classpath:data-h2.sql # 시작할때 실행시킬 script
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
#운영 환경
---
spring.profiles: set1
spring.profiles.include: read-db2

server:
  port: 8081

---
spring.profiles: set2
spring.profiles.include: read-db

server:
  port: 8082