spring :
  profiles :
    active : local # 기본 환경 선택
# local 환경
---
spring :
  config :
    activate :
      on-profile : local
  jpa :
    show-sql : true #sql 보기
    generate-ddl : false
    hibernate :
      naming :
        physical-strategy : org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy : org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties :
      hibernate :
        format_sql : true;  #sql 예쁘게 보기
        ddl-auto : none
        dialect : org.hibernate.dialect.MariaDB53Dialect
  datasource :
    url : jdbc:mariadb://about-me-server.ci2sufiezham.ap-northeast-2.rds.amazonaws.com:3306/aboutme_rds?characterEncoding=UTF-8
    username : admin_aboutme
    password : p98cnd!Y
    driver-class-name : org.mariadb.jdbc.Driver